on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4.1.1
    - uses: avto-dev/markdown-lint@v1
      with:
        args: '.'
        ignore: './LICENSE.md'

